application: sponetube
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /sheets/
  static_dir: statics/sheets

- url: /.*
  script: main.py

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2                                                                  
  version: latest
